name: GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change to ./server
        run: cd server

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          config_file: ./conf.json
          template: clean-jsdoc-theme
          recurse: true
          front_page: ../readme.md
          output_dir: ./out

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out

