name: GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docs
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: /server/src
          config_file: /server/conf.json
          template: clean-jsdoc-theme
          recurse: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          allow_empty_commit: true
          publish_dir: /docs

